### ISSUE TITLE
DONT USE THIS

### ISSUE THREAD

**Issue by frightened-2011** [corbetx/SynapseX-crack#1]
DONT USE THIS IT CONTAINS A TROJAN

**Comment by FatalCreations** [comment]
more importantly does it inject though, if so just run it sandboxed with no internet access, if it's actually cracked their should be all of no reason for it to need network access, the other issue is even the actual uncracked false positives ......

**Comment by FatalCreations** [comment]
but highkey I do believe you, when I was looking at this it was 5 days old with a 9 day account and it's other repos are a personal page and a csgo dll cheat

**Comment by frightened-2011** [comment]
> more importantly does it inject though, if so just run it sandboxed with no internet access, if it's actually cracked their should be all of no reason for it to need network access, the other issue is even the actual uncracked false positives ......

i dont know im stuck on windows 7 on my shitty notebook and dont know how to run a sandbox, vms dont work on my pc

**Comment by FatalCreations** [comment]
Google sandboxie, it's free open source but some features limited without sub, but for basic sandboxing it should be sufficient I'd think, alternatively if vm it sandboxing for some reason isn't an option you could always just make a bootable USB and make sure your windows drive is unmounted while using it. or just use krnl or any other injector that isn't paid to begin with so you don't need cracks

**Comment by FatalCreations** [comment]
lol

**Comment by frightened-2011** [comment]
lmao

**Comment by beliboba** [comment]
https://github.com/corbetx/SynapseX-crack/issues/2
