### ISSUE TITLE
The virus doesn't even work :skull:

### ISSUE THREAD

**Issue by frinkifail** [corbetx/SynapseX-crack#3]

**Comment by frinkifail** [comment]
it errors on launch this is so bad

**Comment by Rolesional** [comment]
its a spyware dont download bro

**Comment by Rolesional** [comment]
and if u need synapse just buy real synapse

**Comment by Rolesional** [comment]
current synapse version is 2.20.9d for today

**Comment by FatalCreations** [comment]
rip @corbetx 
idk what verifications this mans did to say it doesnt even work, but if true thats honestly just sad.
you have all of github to learn to code viruses and somehow you allegedly fk up
